var text = '{"testi":[' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"John","testi":"Doe" },' +
'{"verita":"LIBERI DI SCEGLIERE LA MORTE","testi":"Ippocrate, &#8220Giuramento di Ippocrate&#8221, IV secolo a.C.<br><br>Franjo Cardinale Seper, &#8220Dichiarazione sull’eutanasia&#8221, Roma, sede della Sacra Congregazione per la Dottrina della Fede, 1980<br><br>Consiglio Pontificio, &#8220Questioni etiche relative ai malati gravi e morenti&#8221,Roma, 1981<br><br>&#8220Il quinto comandamento&#8221, in Catechismo della Chiesa, sezione seconda, capitolo secondo, articolo 5, 1997<br><br>Mauro Ronco, &#8220L’indisponibilità della vita: assolutizzazione del principio autonomistico e svuotamento della tutela penale della vita&#8221, in Cristianità n. 341-342 maggio-agosto, 2007<br><br>Beppino Englaro, &#8220La vita estrema&#8221, Beppino Englaro in conversazione con Piero Colaprico, da MicroMega, 2009" },' +
'{"verita":"L&#39 UTERO &Egrave MIO E LO GESTISCO IO","testi":"The Boston Women’s health book collective, &#8220Noi e il nostro corpo, scritto dalle donne per le donne&#8221, Feltrinelli, Milano 1977<br><br>Angela Balzano,Carlo Flamigni, &#8220Sessualità e riproduzione. Due generazioni in dialogo su diritti, corpi e medicina&#8221, Ananke Lab, Torino, 2015<br><br>Margaret Atwood, &#8220Il racconto dell&#39ancella&#8221, Ponte alle Grazie, Firenze, 2017<br><br>Vincenzo Gubitosi, &#8220Autodeterminazione femminista e delirio di onnipotenza&#8221, in Notizie Provita 2018<br><br>Lidia Cirillo, &#8220Utero in affitto o gravidanza per altri? Voci a confronto&#8221, Franco Angeli, Milano, 2017<br><br>Paolo Rodari,&#8220Papa Francesco contro l&#39aborto: E come affittare un sicario per risolvere il problema&#8221, in Repubblica.it, 2018" },' +
'{"verita":"NON C&#39 &Egrave BISOGNO DI CONFINI","testi":"Paul Eluard, &#8220Scrivo il tuo nome, Libertà, in Poesia e verità&#8221, in Poesie, trad. it. di F. Fortini, Mondadori, Milano 1969<br><br>Immanuel Kant, &#8220Per la pace perpetua&#8221 (parte seconda, secondo articolo definitivo), 1975<br><br>Marco Gervasoni, &#8220Altro che guerrafondaio. Il nazionalismo è la virtù di chi resiste agli Imperi&#8221, in Il Giornale.it, 2018" },' +
'{"verita":"L&#39 ITALIA AGLI ITALIANI","testi":"Alfredo Rocco, &#8220Il programma politico<br>dell&#39 associazione nazionalista italiana&#8221, 1919 <br><br>Direzione generale della Comunicazione (Commissione europea), &#8220 60 buone ragioni per cui abbiamo bisogno dell’Unione europea &#8221, Bruxelles 2017" },' +
'{"verita":"L&#39 AMORE NON HA SESSO","testi":"Platone, &#8220Simposio&#8221, IV secolo a.C.<br><br>Wainwright Churchill, &#8220Homosexual Behavior Among Males: A Cross-Cultural and Cross-Species Investigation&#8221, Hawthorn Books, New York 1967<br><br>Martin S. Weinberg, &#8220Homosexuality: a study of diversity among men and women&#8221, Simon & Schuster, New York, 1978<br><br>Maurice Sartre,  &#8220L&#39omosessualità nella nell&#39antica Grecia &#8221, in «L&#39amore e la sessualità», a cura di Georges Duby, Milano, Dedalo, 1986<br><br>Martin Kantor, &#8220Homophobia: Description, Development, and Dynamics of Gay Bashing&#8221, Praeger, New York, 1998<br><br>Massimo Consoli, &#8220Ecce Homo. L&#39omosessualità e la Bibbia&#8221, Kaos Ed., Milano 1999<br><br>Paolo Pedote, &#8220Omofobia. Il pregiudizio anti-omosessuale dalla Bibbia ai giorni nostri&#8221, Stampa Alternativa, Roma 2002<br><br>Maurizio Barbagli, Asher Colombo, &#8220Omosessuali moderni. Gay e lesbiche in Italia&#8221, il Mulino,Bologna, 2007<br><br>Pasquale Quaranta,  &#8220Omosessualità e Vangelo. Franco Barbero risponde &#8221, Gabrielli Editori, Verona, 2008<br><br>Filippo Trasatti, &#8220Contro natura. Omosessualità, Chiesa e biopolitiche&#8221, Elèuthera, Milano 2008<br><br>Simona Argentieri, &#8220A qualcuno piace uguale&#8221, Einaudi, Torino 2010<br><br>Paolo Pedote, &#8220Storia dell&#39 omofobia&#8221, Odoya, Bologna 2011<br><br>Antonio Mocciola, &#8220Addosso. Le parole dell&#39omofobia&#8221, Iemme Edizioni, Napoli 2017<br><br>James Neill, &#8220The Origins and Role of Same-Sex Relations in Human Societies&#8221,McFarland & Company, North Carolina 2011<br><br>Franca Giansoldati, &#8220Papa Francesco: «Sesso dono di Dio da vivere senza tabù, ma solo tra uomo e donna»&#8221, in Il Messaggero.it, 2018" }]}';
